### ISSUE TITLE
Add Columns for proc attributes.

### ISSUE THREAD

**Issue by JnBrymn** [VividCortex/pm-web#6]
A call to http://someserver/procs/ returns a list of procs and each proc is associate with a key-value list of attributes stored in its `attrs` field. We need to display these attributes but currently don't.
# TODO

**All procs page**
- [ ] for each call to pm, for each proc returned collect all of the keys from the attrs object and use them to populate a checkbox list on the side of the screen
- [ ] If someone clicks a box then add the attribute name to the URL in the `attrs` parameter (in the same way we're currently adding hosts to the `hosts` parameter)
- [ ] If someone adds an attribute name to the URL in the `attrs` parameter then checkmark the corresponding selection box (again see the current hosts checkbox implementation for an example)
- [ ] Display all attributes associated with checked boxes in their own columns just to the left of the column with all of the cancel buttons
- [ ] If there is no `attrs` parameter in the URL, automatically add all the attributes to the display (including columns, URLs, and checkboxes).

**Single proc page**
- [ ] Make a new section at the bottom of the page that display all the attributes for the proc. The display should be tabular with two columns, the left is the attribute name and the right is the attribute value.
